import type { LanguageCode } from "../i18n/languages";

// 기초 회화: 한국어 문장과, 이용자 언어의 글자로 적은 한국어 발음. 뜻(번역)은 messages.phrases.items에 둔다.
// 발음은 그 언어를 쓰는 사람이 소리 내어 읽었을 때 한국어에 가깝게 적는다(로마자 표기법 그대로가 아님).

export const PHRASE_GROUPS = {
  greet: ["hello", "thanks", "sorry", "excuse", "yesNo"],
  daily: ["howMuch", "restroom", "thisOne", "menu", "card"],
  emergency: ["help", "police", "hospital", "lost"],
} as const;
export type PhraseGroup = keyof typeof PHRASE_GROUPS;
export type PhraseKey = (typeof PHRASE_GROUPS)[PhraseGroup][number];

export const PHRASE_KO: Record<PhraseKey, string> = {
  hello: "안녕하세요",
  thanks: "감사합니다",
  sorry: "죄송합니다",
  excuse: "실례합니다",
  yesNo: "네 / 아니요",
  howMuch: "이거 얼마예요?",
  restroom: "화장실 어디예요?",
  thisOne: "이거 주세요",
  menu: "영어 메뉴 있어요?",
  card: "카드 돼요?",
  help: "도와주세요!",
  police: "경찰을 불러 주세요",
  hospital: "병원에 가야 해요",
  lost: "길을 잃었어요",
};

type Sounds = Record<PhraseKey, string>;

export const PHRASE_SOUND: Record<Exclude<LanguageCode, "ko">, Sounds> = {
  en: {
    hello: "ahn-nyong-ha-say-yo",
    thanks: "kam-sa-ham-nee-da",
    sorry: "chway-song-ham-nee-da",
    excuse: "shil-leh-ham-nee-da",
    yesNo: "neh / ah-nee-yo",
    howMuch: "ee-guh ol-ma-yeh-yo?",
    restroom: "hwa-jang-shil uh-dee-yeh-yo?",
    thisOne: "ee-guh joo-say-yo",
    menu: "yong-uh meh-nyoo ee-ssuh-yo?",
    card: "ka-deu dweh-yo?",
    help: "doh-wa-joo-say-yo!",
    police: "kyong-cha-reul bool-luh joo-say-yo",
    hospital: "byong-wo-neh ka-ya heh-yo",
    lost: "kee-reul ee-ruh-ssuh-yo",
  },
  ja: {
    hello: "アンニョンハセヨ",
    thanks: "カムサハムニダ",
    sorry: "チェソンハムニダ",
    excuse: "シルレハムニダ",
    yesNo: "ネ / アニヨ",
    howMuch: "イゴ オルマエヨ？",
    restroom: "ファジャンシル オディエヨ？",
    thisOne: "イゴ ジュセヨ",
    menu: "ヨンオ メニュ イッソヨ？",
    card: "カドゥ ドェヨ？",
    help: "トワジュセヨ！",
    police: "キョンチャルル プルロ ジュセヨ",
    hospital: "ピョンウォネ カヤ ヘヨ",
    lost: "キルル イロッソヨ",
  },
  "zh-CN": {
    hello: "安宁哈塞哟",
    thanks: "康桑哈密达",
    sorry: "最送哈密达",
    excuse: "西咧哈密达",
    yesNo: "内 / 啊尼哟",
    howMuch: "一够 哦尔马耶哟？",
    restroom: "花张西尔 哦迪耶哟？",
    thisOne: "一够 珠塞哟",
    menu: "拥哦 么妞 一搜哟？",
    card: "卡的 对哟？",
    help: "偷哇珠塞哟！",
    police: "京擦了 不了 珠塞哟",
    hospital: "病窝内 卡呀 嘿哟",
    lost: "key了 一了搜哟",
  },
  "zh-TW": {
    hello: "安寧哈塞喲",
    thanks: "康桑哈密達",
    sorry: "最送哈密達",
    excuse: "西咧哈密達",
    yesNo: "內 / 啊尼喲",
    howMuch: "一夠 哦爾馬耶喲？",
    restroom: "花張西爾 哦迪耶喲？",
    thisOne: "一夠 珠塞喲",
    menu: "擁哦 麼妞 一搜喲？",
    card: "卡的 對喲？",
    help: "偷哇珠塞喲！",
    police: "京擦了 不了 珠塞喲",
    hospital: "病窩內 卡呀 嘿喲",
    lost: "key了 一了搜喲",
  },
  vi: {
    hello: "an-nhon-ha-xê-yô",
    thanks: "cam-xa-ham-ni-đa",
    sorry: "chuê-xông-ham-ni-đa",
    excuse: "xin-lê-ham-ni-đa",
    yesNo: "nê / a-ni-yô",
    howMuch: "i-gơ ơn-ma-yê-yô?",
    restroom: "hoa-chang-xin ơ-đi-yê-yô?",
    thisOne: "i-gơ chu-xê-yô",
    menu: "yong-ơ mê-niu i-xơ-yô?",
    card: "kha-đư tuê-yô?",
    help: "tô-oa-chu-xê-yô!",
    police: "kiơng-cha-rưl bun-lơ chu-xê-yô",
    hospital: "biơng-uơ-nê ca-ya he-yô",
    lost: "ki-rưl i-rơ-xơ-yô",
  },
  th: {
    hello: "อัน-นยอง-ฮา-เซ-โย",
    thanks: "คัม-ซา-ฮัม-นี-ดา",
    sorry: "ชเว-ซง-ฮัม-นี-ดา",
    excuse: "ชิล-เล-ฮัม-นี-ดา",
    yesNo: "เน / อา-นี-โย",
    howMuch: "อี-กอ ออล-มา-เย-โย?",
    restroom: "ฮวา-จัง-ชิล ออ-ดี-เย-โย?",
    thisOne: "อี-กอ จู-เซ-โย",
    menu: "ยอง-ออ เม-นยู อิด-ซอ-โย?",
    card: "คา-ดือ ดแว-โย?",
    help: "โท-วา-จู-เซ-โย!",
    police: "คยอง-ชา-รึล พุล-ลอ จู-เซ-โย",
    hospital: "พยอง-วอ-เน คา-ยา แฮ-โย",
    lost: "คี-รึล อี-รอ-ซอ-โย",
  },
  id: {
    hello: "an-nyong-ha-se-yo",
    thanks: "kam-sa-ham-ni-da",
    sorry: "cwe-song-ham-ni-da",
    excuse: "sil-le-ham-ni-da",
    yesNo: "ne / a-ni-yo",
    howMuch: "i-go ol-ma-ye-yo?",
    restroom: "hwa-jang-sil o-di-ye-yo?",
    thisOne: "i-go ju-se-yo",
    menu: "yong-o me-nyu i-sso-yo?",
    card: "ka-deu dwe-yo?",
    help: "to-wa-ju-se-yo!",
    police: "kyong-cha-rul pul-lo ju-se-yo",
    hospital: "pyong-wo-ne ka-ya he-yo",
    lost: "ki-rul i-ro-sso-yo",
  },
  es: {
    hello: "an-nyong-ja-se-yo",
    thanks: "kam-sa-jam-ni-da",
    sorry: "chue-song-jam-ni-da",
    excuse: "sil-le-jam-ni-da",
    yesNo: "ne / a-ni-yo",
    howMuch: "i-go ol-ma-ye-yo?",
    restroom: "jua-chang-sil o-di-ye-yo?",
    thisOne: "i-go chu-se-yo",
    menu: "yong-o me-niu i-so-yo?",
    card: "ka-du due-yo?",
    help: "to-ua-chu-se-yo!",
    police: "kiong-cha-rul pul-lo chu-se-yo",
    hospital: "piong-uo-ne ka-ya je-yo",
    lost: "ki-rul i-ro-so-yo",
  },
};
