import type { LanguageCode } from "../i18n/languages";

// 지도 거점 도시와 대표 관광지 (마중 팀이 고른 안내용 데이터).
// 운영 시간·요금처럼 바뀌는 정보는 넣지 않는다. 화면에서 공식 사이트 확인을 안내한다.

export type SpotCategory = "sight" | "food" | "experience" | "shopping" | "night";
type L = Record<LanguageCode, string>;
export type Spot = { category: SpotCategory; name: { ko: string; en: string }; desc: L };
export type City = { id: string; name: L; tagline: L; spots: Spot[] };

export const CITIES: City[] = [
  {
    id: "seoul",
    name: { en: "Seoul", ja: "ソウル", "zh-CN": "首尔", "zh-TW": "首爾", vi: "Seoul", th: "โซล", id: "Seoul", es: "Seúl", ko: "서울" },
    tagline: {
      en: "Palaces, markets and city lights",
      ja: "王宮、市場、そして街の灯り",
      "zh-CN": "宫殿、市场与城市灯火",
      "zh-TW": "宮殿、市場與城市燈火",
      vi: "Cung điện, chợ và ánh đèn thành phố",
      th: "พระราชวัง ตลาด และแสงไฟเมือง",
      id: "Istana, pasar, dan lampu kota",
      es: "Palacios, mercados y luces de la ciudad",
      ko: "궁궐과 시장, 도시의 불빛",
    },
    spots: [
      {
        category: "sight",
        name: { ko: "경복궁", en: "Gyeongbokgung Palace" },
        desc: {
          en: "The main royal palace of the Joseon dynasty. Watch the royal guard ceremony at the gate.",
          ja: "朝鮮王朝の正宮。正門で王宮守門将の交代式が見られます。",
          "zh-CN": "朝鲜王朝的正宫，可以在宫门观看守门将换岗仪式。",
          "zh-TW": "朝鮮王朝的正宮，可在宮門觀看守門將換崗儀式。",
          vi: "Cung điện chính của triều đại Joseon. Có thể xem nghi lễ đổi gác ở cổng.",
          th: "พระราชวังหลักของราชวงศ์โชซ็อน ชมพิธีเปลี่ยนเวรยามที่ประตูได้",
          id: "Istana utama Dinasti Joseon. Saksikan upacara pergantian penjaga di gerbang.",
          es: "El palacio real principal de la dinastía Joseon. Mira el cambio de guardia en la puerta.",
          ko: "조선의 법궁. 정문에서 수문장 교대식을 볼 수 있어요.",
        },
      },
      {
        category: "experience",
        name: { ko: "북촌 한옥마을", en: "Bukchon Hanok Village" },
        desc: {
          en: "Lanes of traditional hanok houses between two palaces. People live here, so keep voices low.",
          ja: "二つの王宮の間に韓屋が並ぶ路地。住民がいるので静かに歩きましょう。",
          "zh-CN": "两座宫殿之间的韩屋小巷。这里有居民生活，请保持安静。",
          "zh-TW": "兩座宮殿之間的韓屋小巷。這裡有居民生活，請保持安靜。",
          vi: "Những con hẻm nhà hanok truyền thống giữa hai cung điện. Có người dân sinh sống, hãy giữ yên lặng.",
          th: "ตรอกบ้านฮันอกดั้งเดิมระหว่างพระราชวังสองแห่ง มีผู้อยู่อาศัย โปรดใช้เสียงเบาๆ",
          id: "Gang rumah hanok tradisional di antara dua istana. Ada warga yang tinggal, jadi jangan berisik.",
          es: "Callejones de casas hanok entre dos palacios. Aquí vive gente, así que habla en voz baja.",
          ko: "두 궁궐 사이 한옥 골목. 주민이 사는 곳이라 조용히 다녀요.",
        },
      },
      {
        category: "night",
        name: { ko: "N서울타워", en: "N Seoul Tower" },
        desc: {
          en: "A tower on Namsan mountain with a wide view of the city at night.",
          ja: "南山の上に立つタワー。夜は街を一望できます。",
          "zh-CN": "南山上的塔，夜晚可以俯瞰整座城市。",
          "zh-TW": "南山上的塔，夜晚可以俯瞰整座城市。",
          vi: "Tháp trên núi Namsan, ngắm toàn cảnh thành phố về đêm.",
          th: "หอคอยบนภูเขานัมซาน ชมวิวเมืองยามค่ำคืนได้กว้างไกล",
          id: "Menara di Gunung Namsan dengan pemandangan kota yang luas di malam hari.",
          es: "Una torre en el monte Namsan con amplias vistas nocturnas de la ciudad.",
          ko: "남산 위의 타워. 밤에는 서울 전체가 내려다보여요.",
        },
      },
      {
        category: "shopping",
        name: { ko: "명동", en: "Myeongdong" },
        desc: {
          en: "Rows of cosmetics shops, with street-food stalls in the evening.",
          ja: "コスメショップが並び、夕方には屋台が出ます。",
          "zh-CN": "化妆品店林立，傍晚还有街头小吃摊。",
          "zh-TW": "化妝品店林立，傍晚還有街頭小吃攤。",
          vi: "Dãy cửa hàng mỹ phẩm, buổi tối có quầy đồ ăn đường phố.",
          th: "ร้านเครื่องสำอางเรียงราย ตอนเย็นมีแผงอาหารริมทาง",
          id: "Deretan toko kosmetik, dengan jajanan kaki lima di malam hari.",
          es: "Tiendas de cosmética y puestos de comida callejera por la tarde.",
          ko: "화장품 가게가 늘어서 있고 저녁엔 길거리 음식 노점이 열려요.",
        },
      },
      {
        category: "food",
        name: { ko: "광장시장", en: "Gwangjang Market" },
        desc: {
          en: "A historic market known for mung-bean pancakes (bindaetteok) and mini gimbap.",
          ja: "緑豆チヂミ(ピンデトック)とミニキンパで有名な老舗市場。",
          "zh-CN": "以绿豆煎饼和迷你紫菜包饭闻名的老市场。",
          "zh-TW": "以綠豆煎餅和迷你紫菜飯捲聞名的老市場。",
          vi: "Chợ lâu đời nổi tiếng với bánh đậu xanh (bindaetteok) và gimbap mini.",
          th: "ตลาดเก่าแก่ ขึ้นชื่อเรื่องแพนเค้กถั่วเขียว (บินแดต็อก) และคิมบับจิ๋ว",
          id: "Pasar bersejarah yang terkenal dengan panekuk kacang hijau (bindaetteok) dan gimbap mini.",
          es: "Mercado histórico famoso por las tortitas de judía mungo (bindaetteok) y el mini gimbap.",
          ko: "빈대떡과 마약김밥으로 유명한 오래된 시장.",
        },
      },
    ],
  },
  {
    id: "incheon",
    name: { en: "Incheon", ja: "仁川", "zh-CN": "仁川", "zh-TW": "仁川", vi: "Incheon", th: "อินชอน", id: "Incheon", es: "Incheon", ko: "인천" },
    tagline: {
      en: "Where most trips begin: port history and Chinatown",
      ja: "旅の始まりの街。港の歴史とチャイナタウン",
      "zh-CN": "多数旅程的起点：港口历史与唐人街",
      "zh-TW": "多數旅程的起點：港口歷史與中華街",
      vi: "Nơi hầu hết chuyến đi bắt đầu: lịch sử cảng và khu phố Tàu",
      th: "จุดเริ่มต้นของหลายทริป ประวัติศาสตร์ท่าเรือและไชน่าทาวน์",
      id: "Titik awal banyak perjalanan: sejarah pelabuhan dan Pecinan",
      es: "Donde empiezan casi todos los viajes: historia portuaria y Chinatown",
      ko: "여행이 시작되는 곳, 개항의 역사와 차이나타운",
    },
    spots: [
      {
        category: "sight",
        name: { ko: "인천 차이나타운", en: "Incheon Chinatown" },
        desc: {
          en: "Korea's best-known Chinatown, home to the Jjajangmyeon Museum.",
          ja: "韓国で最もよく知られたチャイナタウン。ジャジャン麺博物館があります。",
          "zh-CN": "韩国最有名的唐人街，有炸酱面博物馆。",
          "zh-TW": "韓國最有名的中華街，有炸醬麵博物館。",
          vi: "Khu phố Tàu nổi tiếng nhất Hàn Quốc, có Bảo tàng Jjajangmyeon.",
          th: "ไชน่าทาวน์ที่มีชื่อเสียงที่สุดของเกาหลี มีพิพิธภัณฑ์จาจังมยอน",
          id: "Pecinan paling terkenal di Korea, tempat Museum Jjajangmyeon.",
          es: "El Chinatown más conocido de Corea, con el Museo del Jjajangmyeon.",
          ko: "한국에서 가장 잘 알려진 차이나타운. 짜장면박물관이 있어요.",
        },
      },
      {
        category: "food",
        name: { ko: "짜장면", en: "Jjajangmyeon" },
        desc: {
          en: "Black-bean noodles, a Korean-Chinese dish closely tied to this neighborhood.",
          ja: "黒い味噌だれの麺。この街と縁の深い韓国式中華料理です。",
          "zh-CN": "韩式炸酱面，与这一带渊源很深的韩式中餐。",
          "zh-TW": "韓式炸醬麵，與這一帶淵源很深的韓式中餐。",
          vi: "Mì tương đen, món Hoa kiểu Hàn gắn liền với khu phố này.",
          th: "บะหมี่ซอสถั่วดำ อาหารจีนสไตล์เกาหลีที่ผูกพันกับย่านนี้",
          id: "Mi saus kacang hitam, hidangan Korea-Tionghoa yang lekat dengan kawasan ini.",
          es: "Fideos con salsa de soja negra, un plato coreano-chino muy ligado a este barrio.",
          ko: "이 동네와 인연이 깊은 한국식 중화요리.",
        },
      },
      {
        category: "sight",
        name: { ko: "개항장 문화지구", en: "Open Port District" },
        desc: {
          en: "Streets of modern-era buildings from when the port opened in 1883.",
          ja: "1883年の開港当時の近代建築が残る街並み。",
          "zh-CN": "保留着1883年开港时期近代建筑的街区。",
          "zh-TW": "保留著1883年開港時期近代建築的街區。",
          vi: "Những con phố với các tòa nhà cận đại từ khi cảng mở cửa năm 1883.",
          th: "ถนนที่มีอาคารยุคใหม่ตั้งแต่สมัยเปิดท่าเรือในปี 1883",
          id: "Jalan-jalan dengan bangunan era modern sejak pelabuhan dibuka pada 1883.",
          es: "Calles con edificios de la época en que se abrió el puerto, en 1883.",
          ko: "1883년 개항 당시의 근대 건축물이 남은 거리.",
        },
      },
      {
        category: "experience",
        name: { ko: "월미도", en: "Wolmido" },
        desc: {
          en: "A seaside promenade with amusement rides and views of passing ferries.",
          ja: "遊園地の乗り物と行き交うフェリーが見える海沿いの遊歩道。",
          "zh-CN": "有游乐设施、可以看渡轮往来的海边步道。",
          "zh-TW": "有遊樂設施、可以看渡輪往來的海邊步道。",
          vi: "Đường dạo ven biển có trò chơi cảm giác mạnh và ngắm phà qua lại.",
          th: "ทางเดินริมทะเลที่มีเครื่องเล่น และวิวเรือเฟอร์รี่แล่นผ่าน",
          id: "Promenade tepi laut dengan wahana permainan dan pemandangan kapal feri.",
          es: "Paseo marítimo con atracciones y vistas de los ferris que pasan.",
          ko: "놀이기구가 있고 오가는 배가 보이는 바닷가 산책로.",
        },
      },
      {
        category: "night",
        name: { ko: "송도 센트럴파크", en: "Songdo Central Park" },
        desc: {
          en: "A seawater canal park among skyscrapers, good for an evening walk.",
          ja: "高層ビルに囲まれた海水の運河公園。夕方の散歩にぴったり。",
          "zh-CN": "高楼环绕的海水运河公园，适合傍晚散步。",
          "zh-TW": "高樓環繞的海水運河公園，適合傍晚散步。",
          vi: "Công viên kênh nước biển giữa các tòa nhà chọc trời, hợp để dạo buổi tối.",
          th: "สวนคลองน้ำทะเลท่ามกลางตึกระฟ้า เหมาะกับการเดินเล่นยามเย็น",
          id: "Taman kanal air laut di antara gedung pencakar langit, cocok untuk jalan sore.",
          es: "Un parque con canal de agua de mar entre rascacielos, ideal para pasear al atardecer.",
          ko: "고층 빌딩 사이 바닷물 수로 공원. 저녁 산책하기 좋아요.",
        },
      },
    ],
  },
  {
    id: "jeonju",
    name: { en: "Jeonju", ja: "全州", "zh-CN": "全州", "zh-TW": "全州", vi: "Jeonju", th: "จอนจู", id: "Jeonju", es: "Jeonju", ko: "전주" },
    tagline: {
      en: "Hanok streets and a UNESCO City of Gastronomy",
      ja: "韓屋の街並みとユネスコ食文化創造都市",
      "zh-CN": "韩屋街道与联合国教科文组织美食之都",
      "zh-TW": "韓屋街道與聯合國教科文組織美食之都",
      vi: "Phố hanok và Thành phố Ẩm thực của UNESCO",
      th: "ถนนบ้านฮันอกและเมืองแห่งอาหารของยูเนสโก",
      id: "Jalan hanok dan Kota Gastronomi UNESCO",
      es: "Calles de hanok y Ciudad de la Gastronomía de la UNESCO",
      ko: "한옥 거리와 유네스코 음식창의도시",
    },
    spots: [
      {
        category: "sight",
        name: { ko: "전주 한옥마을", en: "Jeonju Hanok Village" },
        desc: {
          en: "Hundreds of traditional hanok houses gathered in the city center.",
          ja: "市内中心部に数百軒の韓屋が集まる村。",
          "zh-CN": "市中心聚集着数百栋传统韩屋。",
          "zh-TW": "市中心聚集著數百棟傳統韓屋。",
          vi: "Hàng trăm ngôi nhà hanok truyền thống tập trung ở trung tâm thành phố.",
          th: "บ้านฮันอกดั้งเดิมหลายร้อยหลังรวมอยู่กลางเมือง",
          id: "Ratusan rumah hanok tradisional berkumpul di pusat kota.",
          es: "Cientos de casas hanok tradicionales reunidas en el centro de la ciudad.",
          ko: "도심에 한옥 수백 채가 모여 있는 마을.",
        },
      },
      {
        category: "food",
        name: { ko: "전주비빔밥", en: "Jeonju Bibimbap" },
        desc: {
          en: "The city's signature rice bowl, mixed with many seasoned toppings.",
          ja: "たくさんの具を混ぜて食べる、この街を代表するご飯料理。",
          "zh-CN": "这座城市的招牌拌饭，配有多种调味配菜。",
          "zh-TW": "這座城市的招牌拌飯，配有多種調味配菜。",
          vi: "Món cơm trộn đặc trưng của thành phố với nhiều loại rau và topping.",
          th: "ข้าวยำประจำเมือง คลุกกับเครื่องเคียงปรุงรสหลายชนิด",
          id: "Nasi campur khas kota ini dengan banyak topping berbumbu.",
          es: "El plato de arroz emblemático de la ciudad, mezclado con muchos acompañamientos.",
          ko: "여러 나물과 고명을 비벼 먹는 전주의 대표 음식.",
        },
      },
      {
        category: "sight",
        name: { ko: "경기전", en: "Gyeonggijeon Shrine" },
        desc: {
          en: "A shrine holding the royal portrait of King Taejo, founder of Joseon.",
          ja: "朝鮮を建国した太祖の御真(肖像画)を祀る場所。",
          "zh-CN": "供奉朝鲜开国君主太祖御真（画像）的地方。",
          "zh-TW": "供奉朝鮮開國君主太祖御真（畫像）的地方。",
          vi: "Nơi lưu giữ chân dung vua Taejo, người sáng lập triều Joseon.",
          th: "ศาลที่ประดิษฐานพระบรมสาทิสลักษณ์ของพระเจ้าแทโจ ผู้ก่อตั้งราชวงศ์โชซ็อน",
          id: "Kuil yang menyimpan potret Raja Taejo, pendiri Dinasti Joseon.",
          es: "Santuario que guarda el retrato real del rey Taejo, fundador de Joseon.",
          ko: "조선을 세운 태조의 어진을 모신 곳.",
        },
      },
      {
        category: "experience",
        name: { ko: "한복 입어 보기", en: "Hanbok rental" },
        desc: {
          en: "Rent traditional Korean clothes and walk the hanok lanes for photos.",
          ja: "韓服をレンタルして、韓屋の路地で写真を撮りましょう。",
          "zh-CN": "租一套韩服，在韩屋小巷里拍照。",
          "zh-TW": "租一套韓服，在韓屋小巷裡拍照。",
          vi: "Thuê hanbok truyền thống và dạo phố hanok chụp ảnh.",
          th: "เช่าชุดฮันบกแล้วเดินถ่ายรูปในตรอกบ้านฮันอก",
          id: "Sewa pakaian tradisional hanbok dan berfoto di gang-gang hanok.",
          es: "Alquila ropa tradicional coreana y pasea por los callejones de hanok para hacer fotos.",
          ko: "한복을 빌려 입고 한옥 골목에서 사진을 찍어요.",
        },
      },
      {
        category: "night",
        name: { ko: "남부시장 야시장", en: "Nambu Night Market" },
        desc: {
          en: "A night market with street-food stalls. Check which evenings it opens.",
          ja: "屋台が並ぶナイトマーケット。営業する曜日を確認しましょう。",
          "zh-CN": "有小吃摊的夜市，出发前请确认开放的日子。",
          "zh-TW": "有小吃攤的夜市，出發前請確認開放的日子。",
          vi: "Chợ đêm với các quầy ăn vặt. Hãy kiểm tra những tối chợ mở cửa.",
          th: "ตลาดกลางคืนที่มีแผงอาหารริมทาง ตรวจสอบวันที่เปิดก่อนไป",
          id: "Pasar malam dengan jajanan kaki lima. Cek malam apa saja buka.",
          es: "Mercado nocturno con puestos de comida. Consulta qué noches abre.",
          ko: "길거리 음식이 모이는 야시장. 여는 요일을 확인하세요.",
        },
      },
    ],
  },
  {
    id: "gyeongju",
    name: { en: "Gyeongju", ja: "慶州", "zh-CN": "庆州", "zh-TW": "慶州", vi: "Gyeongju", th: "คย็องจู", id: "Gyeongju", es: "Gyeongju", ko: "경주" },
    tagline: {
      en: "The thousand-year capital of Silla",
      ja: "新羅千年の都",
      "zh-CN": "新罗千年古都",
      "zh-TW": "新羅千年古都",
      vi: "Kinh đô nghìn năm của Silla",
      th: "เมืองหลวงพันปีของอาณาจักรซิลลา",
      id: "Ibu kota Silla selama seribu tahun",
      es: "La capital milenaria de Silla",
      ko: "천년 신라의 수도",
    },
    spots: [
      {
        category: "sight",
        name: { ko: "불국사", en: "Bulguksa Temple" },
        desc: {
          en: "A Silla-era Buddhist temple and UNESCO World Heritage Site.",
          ja: "新羅時代の仏教寺院で、ユネスコ世界遺産です。",
          "zh-CN": "新罗时代的佛教寺庙，联合国教科文组织世界遗产。",
          "zh-TW": "新羅時代的佛教寺廟，聯合國教科文組織世界遺產。",
          vi: "Ngôi chùa thời Silla, Di sản Thế giới UNESCO.",
          th: "วัดพุทธสมัยซิลลา และมรดกโลกของยูเนสโก",
          id: "Kuil Buddha era Silla dan Situs Warisan Dunia UNESCO.",
          es: "Templo budista de la época Silla, Patrimonio de la Humanidad de la UNESCO.",
          ko: "신라 시대 사찰이자 유네스코 세계유산.",
        },
      },
      {
        category: "sight",
        name: { ko: "석굴암", en: "Seokguram Grotto" },
        desc: {
          en: "A stone Buddha grotto on the mountain above Bulguksa, also UNESCO-listed.",
          ja: "仏国寺の上の山にある石窟の仏像。こちらも世界遺産です。",
          "zh-CN": "佛国寺上方山中的石窟佛像，同样是世界遗产。",
          "zh-TW": "佛國寺上方山中的石窟佛像，同樣是世界遺產。",
          vi: "Hang đá có tượng Phật trên núi phía trên chùa Bulguksa, cũng là di sản UNESCO.",
          th: "ถ้ำพระพุทธรูปหินบนภูเขาเหนือวัดพุลกุกซา เป็นมรดกโลกเช่นกัน",
          id: "Gua Buddha batu di gunung di atas Bulguksa, juga warisan UNESCO.",
          es: "Gruta con un Buda de piedra en la montaña sobre Bulguksa, también de la UNESCO.",
          ko: "불국사 위 산중의 석굴 불상. 함께 세계유산이에요.",
        },
      },
      {
        category: "night",
        name: { ko: "동궁과 월지", en: "Donggung Palace and Wolji Pond" },
        desc: {
          en: "Palace pavilions reflected in the pond. Best after dark.",
          ja: "池に映る宮殿の楼閣。日が暮れてからが見どころです。",
          "zh-CN": "宫殿楼阁倒映在池中，入夜后最美。",
          "zh-TW": "宮殿樓閣倒映在池中，入夜後最美。",
          vi: "Các đình gác cung điện in bóng xuống hồ, đẹp nhất khi trời tối.",
          th: "ศาลาพระราชวังสะท้อนผิวน้ำ สวยที่สุดหลังพลบค่ำ",
          id: "Paviliun istana terpantul di kolam, paling indah setelah gelap.",
          es: "Pabellones del palacio reflejados en el estanque. Mejor de noche.",
          ko: "연못에 비친 전각. 해가 진 뒤가 가장 아름다워요.",
        },
      },
      {
        category: "sight",
        name: { ko: "대릉원", en: "Daereungwon Tomb Complex" },
        desc: {
          en: "Grassy mounds of Silla royal tombs in the middle of the city.",
          ja: "市内の真ん中にある、芝に覆われた新羅の王陵群。",
          "zh-CN": "位于市中心、长满青草的新罗王陵群。",
          "zh-TW": "位於市中心、長滿青草的新羅王陵群。",
          vi: "Những gò mộ hoàng gia Silla phủ cỏ ngay giữa thành phố.",
          th: "เนินสุสานกษัตริย์ซิลลาที่ปกคลุมด้วยหญ้ากลางเมือง",
          id: "Gundukan makam kerajaan Silla berumput di tengah kota.",
          es: "Túmulos cubiertos de hierba de los reyes de Silla en pleno centro.",
          ko: "도심 한가운데 풀로 덮인 신라 왕릉들.",
        },
      },
      {
        category: "shopping",
        name: { ko: "황리단길", en: "Hwangnidan-gil" },
        desc: {
          en: "A hanok-style street of cafés and small shops near the tombs.",
          ja: "古墳のそばにある、カフェや小さな店が並ぶ韓屋風の通り。",
          "zh-CN": "古墓旁韩屋风格的街道，咖啡馆和小店林立。",
          "zh-TW": "古墓旁韓屋風格的街道，咖啡館和小店林立。",
          vi: "Con phố phong cách hanok với quán cà phê và cửa hàng nhỏ gần khu lăng mộ.",
          th: "ถนนสไตล์ฮันอกที่มีคาเฟ่และร้านเล็กๆ ใกล้สุสาน",
          id: "Jalan bergaya hanok dengan kafe dan toko kecil di dekat makam.",
          es: "Calle de estilo hanok con cafés y tiendas pequeñas junto a los túmulos.",
          ko: "왕릉 근처 카페와 작은 가게가 모인 한옥 거리.",
        },
      },
    ],
  },
  {
    id: "busan",
    name: { en: "Busan", ja: "釜山", "zh-CN": "釜山", "zh-TW": "釜山", vi: "Busan", th: "ปูซาน", id: "Busan", es: "Busan", ko: "부산" },
    tagline: {
      en: "Beaches, seafood and hillside villages",
      ja: "ビーチと海の幸、坂の上の村",
      "zh-CN": "海滩、海鲜与山坡村落",
      "zh-TW": "海灘、海鮮與山坡村落",
      vi: "Bãi biển, hải sản và làng trên sườn đồi",
      th: "ชายหาด อาหารทะเล และหมู่บ้านบนเนินเขา",
      id: "Pantai, makanan laut, dan desa di lereng bukit",
      es: "Playas, marisco y pueblos en la ladera",
      ko: "바다와 해산물, 산비탈 마을",
    },
    spots: [
      {
        category: "sight",
        name: { ko: "해운대 해수욕장", en: "Haeundae Beach" },
        desc: {
          en: "Busan's best-known beach, lined with hotels and a long promenade.",
          ja: "釜山で最も有名なビーチ。ホテルと長い遊歩道が続きます。",
          "zh-CN": "釜山最有名的海滩，沿岸是酒店和长长的步道。",
          "zh-TW": "釜山最有名的海灘，沿岸是飯店和長長的步道。",
          vi: "Bãi biển nổi tiếng nhất Busan, dọc theo là khách sạn và đường dạo dài.",
          th: "ชายหาดที่มีชื่อเสียงที่สุดของปูซาน เรียงรายด้วยโรงแรมและทางเดินยาว",
          id: "Pantai paling terkenal di Busan, berderet hotel dan promenade panjang.",
          es: "La playa más conocida de Busan, con hoteles y un largo paseo marítimo.",
          ko: "부산의 대표 해변. 호텔과 긴 산책로가 이어져요.",
        },
      },
      {
        category: "experience",
        name: { ko: "감천문화마을", en: "Gamcheon Culture Village" },
        desc: {
          en: "Colorful houses stacked on a hillside, with art in the alleys.",
          ja: "斜面にカラフルな家が重なり、路地にアート作品がある村。",
          "zh-CN": "五彩房屋层层叠在山坡上，小巷里有艺术作品。",
          "zh-TW": "五彩房屋層層疊在山坡上，小巷裡有藝術作品。",
          vi: "Những ngôi nhà nhiều màu sắc xếp tầng trên sườn đồi, có tranh nghệ thuật trong hẻm.",
          th: "บ้านหลากสีเรียงซ้อนบนเนินเขา มีงานศิลปะตามตรอก",
          id: "Rumah-rumah warna-warni bertingkat di lereng bukit, dengan karya seni di gang.",
          es: "Casas de colores escalonadas en una ladera, con arte en los callejones.",
          ko: "산비탈에 알록달록한 집이 층층이 있고 골목마다 작품이 있어요.",
        },
      },
      {
        category: "food",
        name: { ko: "자갈치시장", en: "Jagalchi Market" },
        desc: {
          en: "A huge seafood market. Pick your fish downstairs and eat it upstairs.",
          ja: "巨大な海鮮市場。下の階で魚を選び、上の階で食べられます。",
          "zh-CN": "超大型海鲜市场，在楼下选鱼，到楼上吃。",
          "zh-TW": "超大型海鮮市場，在樓下選魚，到樓上吃。",
          vi: "Chợ hải sản rất lớn. Chọn cá ở tầng dưới và ăn ở tầng trên.",
          th: "ตลาดอาหารทะเลขนาดใหญ่ เลือกปลาชั้นล่างแล้วขึ้นไปกินชั้นบน",
          id: "Pasar makanan laut yang besar. Pilih ikan di lantai bawah, makan di lantai atas.",
          es: "Un gran mercado de marisco. Elige el pescado abajo y cómelo arriba.",
          ko: "큰 수산시장. 아래층에서 고르고 위층에서 먹어요.",
        },
      },
      {
        category: "sight",
        name: { ko: "해동용궁사", en: "Haedong Yonggungsa Temple" },
        desc: {
          en: "A Buddhist temple built on rocks right by the sea.",
          ja: "海辺の岩の上に建つ仏教寺院。",
          "zh-CN": "建在海边岩石上的佛教寺庙。",
          "zh-TW": "建在海邊岩石上的佛教寺廟。",
          vi: "Ngôi chùa Phật giáo xây trên ghềnh đá sát biển.",
          th: "วัดพุทธที่สร้างบนโขดหินริมทะเล",
          id: "Kuil Buddha yang dibangun di atas batu tepat di tepi laut.",
          es: "Templo budista construido sobre las rocas junto al mar.",
          ko: "바닷가 바위 위에 지은 절.",
        },
      },
      {
        category: "night",
        name: { ko: "광안리 해수욕장", en: "Gwangalli Beach" },
        desc: {
          en: "A beach facing Gwangan Bridge, which lights up at night.",
          ja: "夜にライトアップされる広安大橋を望むビーチ。",
          "zh-CN": "正对广安大桥的海滩，大桥夜晚会亮灯。",
          "zh-TW": "正對廣安大橋的海灘，大橋夜晚會亮燈。",
          vi: "Bãi biển nhìn ra cầu Gwangan rực sáng về đêm.",
          th: "ชายหาดที่หันหน้าสู่สะพานควังอันซึ่งเปิดไฟยามค่ำคืน",
          id: "Pantai yang menghadap Jembatan Gwangan yang menyala di malam hari.",
          es: "Playa frente al puente Gwangan, que se ilumina de noche.",
          ko: "밤이면 불이 켜지는 광안대교를 마주한 해변.",
        },
      },
    ],
  },
  {
    id: "jeju",
    name: { en: "Jeju", ja: "済州", "zh-CN": "济州", "zh-TW": "濟州", vi: "Jeju", th: "เชจู", id: "Jeju", es: "Jeju", ko: "제주" },
    tagline: {
      en: "A volcanic island of trails and sea",
      ja: "トレイルと海の火山島",
      "zh-CN": "步道与大海环绕的火山岛",
      "zh-TW": "步道與大海環繞的火山島",
      vi: "Đảo núi lửa với đường mòn và biển",
      th: "เกาะภูเขาไฟแห่งเส้นทางเดินและทะเล",
      id: "Pulau vulkanik dengan jalur jalan kaki dan laut",
      es: "Una isla volcánica de senderos y mar",
      ko: "길과 바다의 화산섬",
    },
    spots: [
      {
        category: "sight",
        name: { ko: "성산일출봉", en: "Seongsan Ilchulbong" },
        desc: {
          en: "A volcanic crater rising from the sea, UNESCO-listed and famous for sunrise.",
          ja: "海からそびえる火山の噴火口。ユネスコ世界遺産で、日の出の名所です。",
          "zh-CN": "从海中升起的火山口，世界自然遗产，以日出闻名。",
          "zh-TW": "從海中升起的火山口，世界自然遺產，以日出聞名。",
          vi: "Miệng núi lửa nhô lên từ biển, di sản UNESCO, nổi tiếng ngắm bình minh.",
          th: "ปล่องภูเขาไฟที่โผล่จากทะเล เป็นมรดกโลก และขึ้นชื่อเรื่องพระอาทิตย์ขึ้น",
          id: "Kawah gunung api yang menjulang dari laut, warisan UNESCO, terkenal untuk matahari terbit.",
          es: "Un cráter volcánico que surge del mar, de la UNESCO y famoso por sus amaneceres.",
          ko: "바다에서 솟은 분화구. 세계자연유산이자 일출 명소예요.",
        },
      },
      {
        category: "experience",
        name: { ko: "한라산", en: "Hallasan" },
        desc: {
          en: "South Korea's highest mountain, with several hiking trails.",
          ja: "韓国で最も高い山。いくつもの登山道があります。",
          "zh-CN": "韩国最高的山，有多条登山步道。",
          "zh-TW": "韓國最高的山，有多條登山步道。",
          vi: "Ngọn núi cao nhất Hàn Quốc, có nhiều đường leo núi.",
          th: "ภูเขาที่สูงที่สุดในเกาหลีใต้ มีเส้นทางเดินป่าหลายเส้น",
          id: "Gunung tertinggi di Korea Selatan, dengan beberapa jalur pendakian.",
          es: "La montaña más alta de Corea del Sur, con varias rutas de senderismo.",
          ko: "남한에서 가장 높은 산. 등산로가 여러 개 있어요.",
        },
      },
      {
        category: "experience",
        name: { ko: "제주 올레길", en: "Jeju Olle Trail" },
        desc: {
          en: "Walking routes that circle the island along the coast and villages.",
          ja: "海岸と村をつなぎ、島をぐるりと巡るウォーキングコース。",
          "zh-CN": "沿着海岸和村庄环岛的徒步路线。",
          "zh-TW": "沿著海岸和村莊環島的徒步路線。",
          vi: "Những tuyến đi bộ vòng quanh đảo dọc bờ biển và làng mạc.",
          th: "เส้นทางเดินรอบเกาะเลียบชายฝั่งและหมู่บ้าน",
          id: "Rute jalan kaki mengelilingi pulau menyusuri pantai dan desa.",
          es: "Rutas a pie que rodean la isla por la costa y los pueblos.",
          ko: "해안과 마을을 따라 섬을 한 바퀴 도는 걷기 길.",
        },
      },
      {
        category: "food",
        name: { ko: "동문시장", en: "Dongmun Market" },
        desc: {
          en: "A traditional market with a night market and Jeju tangerines.",
          ja: "ナイトマーケットと済州みかんが楽しめる在来市場。",
          "zh-CN": "有夜市和济州柑橘的传统市场。",
          "zh-TW": "有夜市和濟州柑橘的傳統市場。",
          vi: "Chợ truyền thống có chợ đêm và quýt Jeju.",
          th: "ตลาดดั้งเดิมที่มีตลาดกลางคืนและส้มเชจู",
          id: "Pasar tradisional dengan pasar malam dan jeruk Jeju.",
          es: "Mercado tradicional con mercado nocturno y mandarinas de Jeju.",
          ko: "야시장과 제주 귤을 만날 수 있는 전통시장.",
        },
      },
      {
        category: "food",
        name: { ko: "제주 흑돼지", en: "Jeju Black Pork" },
        desc: {
          en: "Grilled black pork, a local specialty of the island.",
          ja: "島の名物、黒豚の焼肉。",
          "zh-CN": "岛上特产，烤黑猪肉。",
          "zh-TW": "島上特產，烤黑豬肉。",
          vi: "Thịt heo đen nướng, đặc sản của đảo.",
          th: "หมูดำย่าง อาหารขึ้นชื่อของเกาะ",
          id: "Babi hitam panggang, makanan khas pulau ini.",
          es: "Cerdo negro a la parrilla, especialidad de la isla.",
          ko: "섬의 명물, 흑돼지 구이.",
        },
      },
    ],
  },
];

export const CATEGORY_ORDER: SpotCategory[] = ["sight", "food", "experience", "shopping", "night"];
